"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Search } from "lucide-react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { caseCategories, caseNotes, matchesCaseCategory, type CaseNote } from "@/data/caseNotes";

export function CasesArchive(){
 const root=useRef<HTMLDivElement>(null),grid=useRef<HTMLElement>(null); const [category,setCategory]=useState("전체"),[query,setQuery]=useState(""),[page,setPage]=useState(0);
 const filtered=useMemo(()=>caseNotes.filter(n=>matchesCaseCategory(n,category)&&(!query.trim()||`${n.title} ${n.category} ${n.issue}`.toLowerCase().includes(query.trim().toLowerCase()))),[category,query]);
 const pageSize=8,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice(page*pageSize,(page+1)*pageSize);
 useEffect(()=>setPage(0),[category,query]);
 useEffect(()=>{if(!grid.current||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.fromTo(grid.current.querySelectorAll(".case-card"),{autoAlpha:0,x:24},{autoAlpha:1,x:0,duration:.48,stagger:.035,ease:"power3.out"})},[page,category,query]);
 useEffect(()=>{if(!root.current)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.timeline().from(".cases-kicker",{x:-18,opacity:0,duration:.5}).from(".cases-title-line",{yPercent:105,scaleY:.78,duration:.85,stagger:.1,ease:"power3.out"},.08).from(".cases-intro",{y:18,opacity:0,duration:.65},.35).from(".case-card-visual",{clipPath:"inset(100% 0 0 0)",duration:.7,stagger:.06,ease:"power3.out"},.55);gsap.to(".cases-title",{yPercent:-14,opacity:.22,ease:"none",scrollTrigger:{trigger:".cases-hero",start:"top top",end:"bottom top",scrub:true}})},root);return()=>ctx.revert()},[]);
 return <div className="cases-page" ref={root}><section className="cases-hero"><div><p className="cases-kicker">CASE STUDY ARCHIVE</p><h1 className="cases-title"><span><i className="cases-title-line">COADS</i></span><span><i className="cases-title-line">CASENOTE</i></span></h1></div><div className="cases-intro"><p>온라인에서 발생한 문제와 대응 사례를 기록합니다.</p><small>브랜드 · 개인 · 인플루언서 · 검색 · 커뮤니티 · SNS</small></div></section><div className="cases-toolbar"><div className="cases-filters">{caseCategories.map(c=><button key={c} className={category===c?"active":""} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="cases-search"><span className="sr-only">사례 검색</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="CASE SEARCH"/><Search size={20}/></label></div><section className="cases-grid" ref={grid}>{visible.map(n=><CaseCard key={n.slug} note={n}/>)}</section>{!filtered.length&&<p className="cases-empty">일치하는 사례가 없습니다.</p>}{filtered.length>0&&<nav className="cases-slider-nav" aria-label="사례 페이지 이동"><button disabled={page===0} onClick={()=>setPage(v=>Math.max(0,v-1))} aria-label="이전 사례"><ArrowLeft/></button><p><b>{String(page+1).padStart(2,"0")}</b><span>/</span>{String(totalPages).padStart(2,"0")}</p><div className="cases-slider-track"><i style={{width:`${((page+1)/totalPages)*100}%`}}/></div><button disabled={page>=totalPages-1} onClick={()=>setPage(v=>Math.min(totalPages-1,v+1))} aria-label="다음 사례"><ArrowRight/></button></nav>}</div>
}
function CaseCard({note}:{note:CaseNote}){return <Link href={`/cases/${note.slug}`} className="case-card" style={{"--accent":note.accent} as React.CSSProperties}><div className={`case-card-visual cover-${note.coverType}`}><MiniScreen note={note}/><div className="case-hover"><b>ISSUE</b><p>{note.issue}</p><b>RESPONSE</b><p>{note.response}</p><span>VIEW CASE <ArrowRight size={18}/></span></div></div><div className="case-caption"><small>{String(note.id).padStart(2,"0")} · {note.category}</small><h2>{note.title}</h2></div></Link>}
function MiniScreen({note}:{note:CaseNote}){return <div className="case-screen"><header>COADS SIGNAL <i/></header>{note.coverType==="search"&&<><div className="fake-search"><Search size={18}/>{note.title}</div>{[1,2,3].map(i=><p key={i} className="fake-result">검색 결과 {i}<span/></p>)}</>}{note.coverType==="community"&&<><h3><em>Q.</em> {note.title}</h3><p>익명 사용자의 질문과 답변이 반복 노출되고 있습니다.</p><p>답변 23 · 조회 8,734</p></>}{note.coverType==="news"&&<><div className="building"/><h3>{note.title}</h3></>}{note.coverType==="video"&&<><div className="player">▶　0:00 / 1:24</div>{["맥락이 잘린 편집본","실제 발언 확인 필요","사실관계 확인"].map(x=><p key={x}>{x}</p>)}</>}{note.coverType==="review"&&<div className="reviews">{[1,2,3,4].map(i=><p key={i}>★★☆☆☆<br/>익명 리뷰 {i}</p>)}</div>}{note.coverType==="social"&&<><h3>@anonymous_signal</h3><p>{note.title}<br/>관련 내용이 확산 중입니다.</p><footer>♡ 78　↗ 23　◌ 12</footer></>}{note.coverType==="message"&&<blockquote>“{note.title}”<small>익명 제보 · 2026.08.05</small></blockquote>}{note.coverType==="document"&&<><h3>EVIDENCE NOTE</h3>{[1,2,3,4].map(i=><p key={i} className={i===2?"mark":""}>주요 문장 및 기록 {i}</p>)}</>}</div>}
